title: Dennis Nyaaba 
logo: IMG-20230808-WA0012.jpg
description: Very Calm and welcomes any suggestions and ideas 
show_dowloads: true
image: ![image_859540174131631179796633](https://github.com/Truth300/truth_data/blob/main/image_859540174131631179796633.png)
theme: jekyll-theme-minimal
